language: node_js
node_js:
  - "10"
os:
  - osx
  - windows
  - linux
dist: trusty
cache:
  directories:
    - "node_modules"
    - $HOME/.cache/electron

env:
  - YARN_GPG=no

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/

before_install:
  - npm i -g yarn
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install dpkg fakeroot          ; fi
install:
  - yarn
script:
  - npm run make
