language: node_js
node_js:
  - "10"
os:
  - osx
dist: trusty
cache:
  directories:
    - "node_modules"
    - $HOME/.cache/electron

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/

before_install:
  - npm i -g yarn
install:
  - yarn
script:
  - npm run make
