language: node_js
node_js:
  - "10"
os:
  - osx
  - windows
  - linux
dist: bionic
cache:
  directories:
    - "node_modules"
    - $HOME/.cache/electron

env:
  - YARN_GPG=no

branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+/

before_install:
  - npm i -g yarn
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update && sudo apt-get install dpkg fakeroot rpm; fi
install:
  - yarn
script:
  - npm run make

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file_glob: true
  file:
    - out/make/*
    - out/make/zip/darwin/x64/*
    - out/make/rpm/x64/*
    - out/make/deb/x64/*
    - out/make/squirrel.windows/x64/*
  skip_cleanup: true
  draft: true
